name       : python-casttube
version    : 0.2.0
release    : 3
source     :
    - https://pypi.python.org/packages/source/c/casttube/casttube-0.2.0.tar.gz : f25b3c634efe702896233690f7590e8d6311590910f18dbb763b90419d9ef53c
license    : MIT
component  : programming.python
summary    : YouTube Chromecast API
description: |
    casttube provides a way to interact with the Youtube Chromecast api.
rundeps    :
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
